version: '3'
services:
  weather_api:
    container_name: backend
    build: ./weather_api/
    ports:
      - "3000:3000"
    networks:
      - first_network
  telegram_bot:
    container_name: telegram
    build: ./telegram_bot/
    depends_on:
      - weather_api
    networks:
      - first_network
networks:
  first_network: